version: '3'
services:
  db:
    restart: always
    image: postgres:11
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgbackups3:
    image: lm4992/postgres-backup-s3
    links:
      - db
    environment:
      SCHEDULE: '@daily'
      S3_REGION: us-west-1
      S3_ACCESS_KEY_ID: ${AWS_KEY}
      S3_SECRET_ACCESS_KEY: ${AWS_SECRET}
      S3_BUCKET: beehive-db-backups
      S3_PREFIX: backups
      POSTGRES_DATABASE: postgres
      POSTGRES_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD:
      POSTGRES_EXTRA_OPTS: '--schema=public --blobs'

  web:
    restart: always
    build: .
    volumes:
      - .:/application
    ports:
      - "3000:3000"
      - "${PORT}:3000"
    depends_on:
      - db
    env_file:
      - .env
