development:
    adapter: postgresql
    database: dc8gh7b3pjl8l3
    host: localhost
    username: postgres
    password: gobears
    pool: 5
    timeout: 5000

test:
    adapter: postgresql
    database: dc8gh7b3pjl8l3
    host: localhost
    username: postgres
    password: gobears
    pool: 5
    timeout: 5000
